"""
Synthesized capability: average_salary_by_department
Calculate the average salary for each department from employee records.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    rows = args.get('rows', [])
    
    # Group salaries by department
    department_salaries = {}
    for row in rows:
        dept = row.get('department')
        salary = row.get('salary')
        if dept and salary is not None:
            if dept not in department_salaries:
                department_salaries[dept] = []
            department_salaries[dept].append(salary)
    
    # Calculate average salary per department
    average_salary_by_department = {}
    for dept, salaries in department_salaries.items():
        average_salary_by_department[dept] = sum(salaries) / len(salaries)
    
    # Calculate overall average
    all_salaries = [s for salaries in department_salaries.values() for s in salaries]
    overall_average = sum(all_salaries) / len(all_salaries) if all_salaries else 0
    
    return {
        'average_salary_by_department': average_salary_by_department,
        'summary': {
            'total_departments': len(average_salary_by_department),
            'overall_average_salary': overall_average,
            'total_employees': len(rows)
        }
    }
