"""
Synthesized capability: correlation_heatmap
Generate a correlation heatmap visualization from numeric columns in the dataset.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

import io
import base64
import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict

def run(args):
    rows = args.get('rows', [])
    columns = args.get('columns', [])
    
    if not rows or not columns:
        return {'error': 'No data provided', 'image_base64': None}
    
    # Extract numeric columns and build a numeric data matrix
    numeric_data = defaultdict(list)
    
    for row in rows:
        for col in columns:
            val = row.get(col, None)
            if val is None or val == '':
                numeric_data[col].append(np.nan)
            else:
                # Try to parse as float, handling common formats
                try:
                    # Remove common non-numeric characters
                    cleaned = str(val).strip()
                    cleaned = cleaned.replace('$', '').replace(',', '').replace('kms', '').replace('%', '').strip()
                    numeric_data[col].append(float(cleaned))
                except (ValueError, TypeError):
                    numeric_data[col].append(np.nan)
    
    # Filter to only columns with at least some numeric data
    numeric_cols = [col for col in columns if col in numeric_data and not all(np.isnan(numeric_data[col]))]
    
    if len(numeric_cols) < 2:
        return {'error': 'Need at least 2 numeric columns for correlation', 'image_base64': None}
    
    # Build correlation matrix
    data_matrix = np.array([numeric_data[col] for col in numeric_cols]).T
    
    # Calculate correlation, ignoring NaN values
    corr_matrix = np.corrcoef(data_matrix, rowvar=False)
    
    # Create heatmap
    fig, ax = plt.subplots(figsize=(10, 8))
    
    im = ax.imshow(corr_matrix, cmap='coolwarm', aspect='auto', vmin=-1, vmax=1)
    
    # Set ticks and labels
    ax.set_xticks(np.arange(len(numeric_cols)))
    ax.set_yticks(np.arange(len(numeric_cols)))
    ax.set_xticklabels(numeric_cols, rotation=45, ha='right')
    ax.set_yticklabels(numeric_cols)
    
    # Add correlation values as text
    for i in range(len(numeric_cols)):
        for j in range(len(numeric_cols)):
            text = ax.text(j, i, f'{corr_matrix[i, j]:.2f}',
                          ha="center", va="center", color="black", fontsize=9)
    
    ax.set_title('Correlation Heatmap', fontsize=14, fontweight='bold')
    fig.colorbar(im, ax=ax, label='Correlation Coefficient')
    plt.tight_layout()
    
    # Save to base64
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=100, bbox_inches='tight')
    buf.seek(0)
    image_base64 = base64.b64encode(buf.read()).decode('utf-8')
    plt.close(fig)
    
    return {
        'image_base64': image_base64,
        'numeric_columns': numeric_cols,
        'correlation_matrix': corr_matrix.tolist()
    }
