"""
Synthesized capability: correlation_between_age_and_salary
Calculates the Pearson correlation coefficient between age and salary to quantify their linear relationship.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import statistics
    
    rows = args.get('rows', [])
    column1 = args.get('column1', 'age')
    column2 = args.get('column2', 'salary')
    
    # Extract values for both columns
    values1 = []
    values2 = []
    
    for row in rows:
        if column1 in row and column2 in row:
            val1 = row[column1]
            val2 = row[column2]
            # Only include if both values are numeric
            if isinstance(val1, (int, float)) and isinstance(val2, (int, float)):
                values1.append(val1)
                values2.append(val2)
    
    # Need at least 2 data points to compute correlation
    if len(values1) < 2:
        return {
            'correlation': None,
            'count': len(values1),
            'error': 'Insufficient data points for correlation calculation'
        }
    
    # Calculate means
    mean1 = statistics.mean(values1)
    mean2 = statistics.mean(values2)
    
    # Calculate standard deviations
    stdev1 = statistics.stdev(values1)
    stdev2 = statistics.stdev(values2)
    
    # Handle case where standard deviation is zero
    if stdev1 == 0 or stdev2 == 0:
        return {
            'correlation': None,
            'count': len(values1),
            'error': 'Cannot compute correlation: one or both columns have zero variance'
        }
    
    # Calculate Pearson correlation coefficient
    numerator = sum((values1[i] - mean1) * (values2[i] - mean2) for i in range(len(values1)))
    denominator = stdev1 * stdev2 * (len(values1) - 1)
    
    correlation = numerator / denominator
    
    return {
        'correlation': round(correlation, 4),
        'column1': column1,
        'column2': column2,
        'count': len(values1),
        'mean_column1': round(mean1, 2),
        'mean_column2': round(mean2, 2),
        'stdev_column1': round(stdev1, 2),
        'stdev_column2': round(stdev2, 2)
    }
