"""
Synthesized capability: count_employees_by_city
Count the number of employees in each city and return results sorted by count in descending order.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    rows = args.get('rows', [])
    sort_order = args.get('sort_order', 'descending')
    
    # Count employees by city
    city_counts = {}
    for row in rows:
        city = row.get('city')
        if city:
            city_counts[city] = city_counts.get(city, 0) + 1
    
    # Convert to list of dicts and sort
    city_list = [{'city': city, 'count': count} for city, count in city_counts.items()]
    
    # Sort by count
    reverse = (sort_order.lower() == 'descending')
    city_list.sort(key=lambda x: x['count'], reverse=reverse)
    
    # Calculate total
    total_employees = sum(item['count'] for item in city_list)
    
    return {
        'city_counts': city_list,
        'total_employees': total_employees
    }
