"""
Synthesized capability: plot_regulatory_score_distribution
Generate a histogram visualization of the Regulatory Score distribution from genomic data.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

import matplotlib.pyplot as plt
import io
import base64
from statistics import mean, stdev

def run(args):
    rows = args.get('rows', [])
    plot_type = args.get('plot_type', 'histogram')
    
    # Extract regulatory_score values from rows
    regulatory_scores = []
    for row in rows:
        try:
            score = float(row.get('regulatory_score', 0))
            regulatory_scores.append(score)
        except (ValueError, TypeError):
            continue
    
    if not regulatory_scores:
        return {
            'error': 'No valid regulatory scores found in data',
            'image_base64': None
        }
    
    # Create figure and plot
    fig, ax = plt.subplots(figsize=(10, 6))
    
    if plot_type.lower() == 'histogram':
        ax.hist(regulatory_scores, bins=30, color='steelblue', edgecolor='black', alpha=0.7)
        ax.set_xlabel('Regulatory Score', fontsize=12)
        ax.set_ylabel('Frequency', fontsize=12)
        ax.set_title('Regulatory Score Distribution', fontsize=14, fontweight='bold')
    else:
        # Default to histogram if plot_type is not recognized
        ax.hist(regulatory_scores, bins=30, color='steelblue', edgecolor='black', alpha=0.7)
        ax.set_xlabel('Regulatory Score', fontsize=12)
        ax.set_ylabel('Frequency', fontsize=12)
        ax.set_title('Regulatory Score Distribution', fontsize=14, fontweight='bold')
    
    ax.grid(axis='y', alpha=0.3)
    
    # Calculate statistics
    mean_score = mean(regulatory_scores)
    stdev_score = stdev(regulatory_scores) if len(regulatory_scores) > 1 else 0
    min_score = min(regulatory_scores)
    max_score = max(regulatory_scores)
    
    # Add statistics text to plot
    stats_text = f'Mean: {mean_score:.4f}\nStd Dev: {stdev_score:.4f}\nMin: {min_score:.4f}\nMax: {max_score:.4f}'
    ax.text(0.98, 0.97, stats_text, transform=ax.transAxes, 
            fontsize=10, verticalalignment='top', horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    plt.tight_layout()
    
    # Save to base64
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png', dpi=100, bbox_inches='tight')
    buffer.seek(0)
    image_base64 = base64.b64encode(buffer.read()).decode('utf-8')
    plt.close(fig)
    
    return {
        'image_base64': image_base64,
        'statistics': {
            'mean': round(mean_score, 4),
            'stdev': round(stdev_score, 4),
            'min': round(min_score, 4),
            'max': round(max_score, 4),
            'count': len(regulatory_scores)
        }
    }
