"""
Synthesized capability: london_weather_app_display
Displays London weather with temperature in Celsius and Fahrenheit, calculated heat index, humidity, wind speed, and weather warnings.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import json
    import requests
    import uuid
    from math import exp
    
    # Preserve existing elements
    existing = args.get("elements", [])
    if isinstance(existing, str):
        try:
            existing = json.loads(existing)
        except:
            existing = []
    
    elements = []
    
    # Fetch London weather data
    try:
        # 1. Geocode London
        geo_url = "https://geocoding-api.open-meteo.com/v1/search?name=London&count=1&language=en"
        geo_resp = requests.get(geo_url, timeout=20)
        geo_data = geo_resp.json()
        
        if not geo_data.get("results"):
            return {"elements": [], "summary": "Failed to fetch London location data"}
        
        lat = geo_data["results"][0]["latitude"]
        lon = geo_data["results"][0]["longitude"]
        
        # 2. Fetch current weather
        weather_url = (
            f"https://api.open-meteo.com/v1/forecast?"
            f"latitude={lat}&longitude={lon}"
            f"&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code,apparent_temperature"
            f"&wind_speed_unit=kmh&timezone=auto"
        )
        weather_resp = requests.get(weather_url, timeout=20)
        weather_data = weather_resp.json()
        current = weather_data.get("current", {})
        
        temp_c = current.get("temperature_2m", 0)
        humidity = current.get("relative_humidity_2m", 0)
        feels_c = current.get("apparent_temperature", 0)
        wind_kmh = current.get("wind_speed_10m", 0)
        weather_code = current.get("weather_code", 0)
        
        # 3. Convert to Fahrenheit
        temp_f = temp_c * 9/5 + 32
        feels_f = feels_c * 9/5 + 32
        
        # 4. Calculate heat index (Rothfusz regression)
        # HI = -42.379 + 2.04901523*T + 10.14333127*RH - 0.22475541*T*RH - 0.00683783*T^2 - 0.05481717*RH^2 + 0.00122874*T^2*RH + 0.00085282*T*RH^2 - 0.00000199*T^2*RH^2
        c1, c2, c3, c4, c5, c6, c7, c8, c9 = -42.379, 2.04901523, 10.14333127, -0.22475541, -0.00683783, -0.05481717, 0.00122874, 0.00085282, -0.00000199
        hi_f = (c1 + c2*temp_f + c3*humidity + c4*temp_f*humidity + c5*temp_f**2 + 
                c6*humidity**2 + c7*temp_f**2*humidity + c8*temp_f*humidity**2 + c9*temp_f**2*humidity**2)
        hi_c = (hi_f - 32) * 5/9
        
        # 5. Determine weather condition and warnings
        weather_desc = {
            0: "Clear sky",
            1: "Mainly clear",
            2: "Partly cloudy",
            3: "Overcast",
            45: "Foggy",
            48: "Depositing rime fog",
            51: "Light drizzle",
            53: "Moderate drizzle",
            55: "Dense drizzle",
            61: "Slight rain",
            63: "Moderate rain",
            65: "Heavy rain",
            71: "Slight snow",
            73: "Moderate snow",
            75: "Heavy snow",
            77: "Snow grains",
            80: "Slight rain showers",
            81: "Moderate rain showers",
            82: "Violent rain showers",
            85: "Slight snow showers",
            86: "Heavy snow showers",
            95: "Thunderstorm",
            96: "Thunderstorm with slight hail",
            99: "Thunderstorm with heavy hail"
        }.get(weather_code, "Unknown")
        
        # Determine warnings
        warnings = []
        if hi_f > 103:
            warnings.append("⚠️ EXTREME HEAT: Heat index above 103°F")
        elif hi_f > 95:
            warnings.append("⚠️ HIGH HEAT: Heat index above 95°F")
        
        if weather_code in [95, 96, 99]:
            warnings.append("⚠️ THUNDERSTORM WARNING")
        elif weather_code in [65, 82, 86]:
            warnings.append("⚠️ HEAVY PRECIPITATION")
        
        if wind_kmh > 50:
            warnings.append("⚠️ HIGH WIND WARNING")
        
        warning_text = "\n".join(warnings) if warnings else "✓ No active warnings"
        
    except Exception as e:
        return {"elements": [], "summary": f"Error fetching weather: {str(e)}"}
    
    # Build canvas elements
    # Background
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": 0,
        "y": 0,
        "w": 1200,
        "h": 700,
        "fill": "#f8f9fc",
        "stroke": "none",
        "label": "Canvas background"
    })
    
    # Main card background
    card_w, card_h = 1000, 600
    card_x, card_y = (1200 - card_w) / 2, 50
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": card_x,
        "y": card_y,
        "w": card_w,
        "h": card_h,
        "fill": "#f0f4ff",
        "stroke": "#6c8cff",
        "opacity": 1,
        "rx": 12,
        "label": "Main card"
    })
    
    # Title
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 30,
        "w": 400,
        "h": 50,
        "text": "London Weather",
        "fontSize": 40,
        "fill": "#1b1f2a",
        "label": "Title"
    })
    
    # Current condition
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 90,
        "w": 400,
        "h": 30,
        "text": weather_desc,
        "fontSize": 20,
        "fill": "#8b94a7",
        "label": "Weather condition"
    })
    
    # Temperature section (left column)
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 150,
        "w": 200,
        "h": 25,
        "text": "Temperature",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Temp label"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 180,
        "w": 300,
        "h": 50,
        "text": f"{temp_c:.1f}°C / {temp_f:.1f}°F",
        "fontSize": 36,
        "fill": "#6c8cff",
        "label": "Temperature display"
    })
    
    # Feels like
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 240,
        "w": 200,
        "h": 25,
        "text": "Feels Like",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Feels like label"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 270,
        "w": 300,
        "h": 40,
        "text": f"{feels_c:.1f}°C / {feels_f:.1f}°F",
        "fontSize": 28,
        "fill": "#36d399",
        "label": "Feels like display"
    })
    
    # Heat index section (right column)
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 550,
        "y": card_y + 150,
        "w": 200,
        "h": 25,
        "text": "Heat Index",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Heat index label"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 550,
        "y": card_y + 180,
        "w": 350,
        "h": 50,
        "text": f"{hi_c:.1f}°C / {hi_f:.1f}°F",
        "fontSize": 36,
        "fill": "#ffb454",
        "label": "Heat index display"
    })
    
    # Humidity
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 550,
        "y": card_y + 240,
        "w": 200,
        "h": 25,
        "text": "Humidity",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Humidity label"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 550,
        "y": card_y + 270,
        "w": 300,
        "h": 40,
        "text": f"{humidity:.0f}%",
        "fontSize": 28,
        "fill": "#6c8cff",
        "label": "Humidity display"
    })
    
    # Wind speed
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 330,
        "w": 200,
        "h": 25,
        "text": "Wind Speed",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Wind label"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 40,
        "y": card_y + 360,
        "w": 300,
        "h": 40,
        "text": f"{wind_kmh:.1f} km/h",
        "fontSize": 24,
        "fill": "#1b1f2a",
        "label": "Wind display"
    })
    
    # Warnings section
    warning_color = "#ffb454" if warnings else "#36d399"
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": card_x + 40,
        "y": card_y + 420,
        "w": 920,
        "h": 140,
        "fill": "#fff9f0" if warnings else "#f0fff4",
        "stroke": warning_color,
        "rx": 8,
        "label": "Warnings box"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 60,
        "y": card_y + 435,
        "w": 880,
        "h": 110,
        "text": warning_text,
        "fontSize": 16,
        "fill": "#1b1f2a",
        "label": "Warnings text"
    })
    
    return {
        "elements": elements,
        "summary": f"London weather app: {temp_c:.1f}°C ({temp_f:.1f}°F), heat index {hi_c:.1f}°C ({hi_f:.1f}°F), {len(warnings)} active warnings"
    }
