"""
Synthesized capability: mobile_login_screen
Creates a customizable mobile app login screen with email/password fields, sign-in button, and optional social login and sign-up links.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import json
    import uuid
    
    # Start fresh for a login screen (new design, not editing existing)
    elements = []
    
    # Read customization args with sensible defaults
    app_name = args.get("app_name", "MyApp")
    primary_color = args.get("primary_color", "#6c8cff")
    show_signup_link = args.get("show_signup_link", True)
    show_forgot_password = args.get("show_forgot_password", True)
    show_social_login = args.get("show_social_login", False)
    
    # Canvas dimensions
    canvas_w, canvas_h = 1200, 700
    
    # ─────────────────────────────────────────────────────────────
    # Background
    # ─────────────────────────────────────────────────────────────
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": 0,
        "y": 0,
        "w": canvas_w,
        "h": canvas_h,
        "fill": "#f8f9fc",
        "stroke": "none",
        "label": "Canvas Background"
    })
    
    # ─────────────────────────────────────────────────────────────
    # Left side: Branding / Hero section (optional visual)
    # ─────────────────────────────────────────────────────────────
    left_panel_w = 400
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": 0,
        "y": 0,
        "w": left_panel_w,
        "h": canvas_h,
        "fill": primary_color,
        "stroke": "none",
        "label": "Left Panel (Branding)"
    })
    
    # App name / logo area on left
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": 50,
        "y": 80,
        "w": 300,
        "h": 60,
        "text": app_name,
        "fontSize": 48,
        "fill": "#e6e9ef",
        "label": "App Name"
    })
    
    # Tagline on left
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": 50,
        "y": 160,
        "w": 300,
        "h": 40,
        "text": "Welcome back",
        "fontSize": 24,
        "fill": "#e6e9ef",
        "label": "Tagline"
    })
    
    # ─────────────────────────────────────────────────────────────
    # Right side: Login form card
    # ─────────────────────────────────────────────────────────────
    card_w = 380
    card_h = 500
    card_x = (canvas_w - left_panel_w - card_w) / 2 + left_panel_w
    card_y = (canvas_h - card_h) / 2
    
    # Card background
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": card_x,
        "y": card_y,
        "w": card_w,
        "h": card_h,
        "fill": "#f0f4ff",
        "stroke": "#e0e6ff",
        "rx": 12,
        "label": "Login Card"
    })
    
    # Card title
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": card_x + 30,
        "y": card_y + 30,
        "w": card_w - 60,
        "h": 40,
        "text": "Sign In",
        "fontSize": 32,
        "fill": "#1b1f2a",
        "label": "Card Title"
    })
    
    # ─────────────────────────────────────────────────────────────
    # Email input field
    # ─────────────────────────────────────────────────────────────
    input_w = card_w - 60
    input_h = 48
    input_x = card_x + 30
    
    # Email label
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": input_x,
        "y": card_y + 90,
        "w": input_w,
        "h": 18,
        "text": "Email",
        "fontSize": 14,
        "fill": "#1b1f2a",
        "label": "Email Label"
    })
    
    # Email input box
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": input_x,
        "y": card_y + 115,
        "w": input_w,
        "h": input_h,
        "fill": "#ffffff",
        "stroke": "#d0d8e8",
        "rx": 6,
        "label": "Email Input"
    })
    
    # Email placeholder text
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": input_x + 15,
        "y": card_y + 130,
        "w": input_w - 30,
        "h": 18,
        "text": "you@example.com",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Email Placeholder"
    })
    
    # ─────────────────────────────────────────────────────────────
    # Password input field
    # ─────────────────────────────────────────────────────────────
    
    # Password label
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": input_x,
        "y": card_y + 185,
        "w": input_w,
        "h": 18,
        "text": "Password",
        "fontSize": 14,
        "fill": "#1b1f2a",
        "label": "Password Label"
    })
    
    # Password input box
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": input_x,
        "y": card_y + 210,
        "w": input_w,
        "h": input_h,
        "fill": "#ffffff",
        "stroke": "#d0d8e8",
        "rx": 6,
        "label": "Password Input"
    })
    
    # Password placeholder (dots)
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": input_x + 15,
        "y": card_y + 225,
        "w": input_w - 30,
        "h": 18,
        "text": "••••••••",
        "fontSize": 16,
        "fill": "#8b94a7",
        "label": "Password Placeholder"
    })
    
    # ─────────────────────────────────────────────────────────────
    # Forgot password link (if enabled)
    # ─────────────────────────────────────────────────────────────
    if show_forgot_password:
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "text",
            "x": input_x,
            "y": card_y + 275,
            "w": input_w,
            "h": 18,
            "text": "Forgot password?",
            "fontSize": 14,
            "fill": primary_color,
            "label": "Forgot Password Link"
        })
    
    # ─────────────────────────────────────────────────────────────
    # Sign In button
    # ─────────────────────────────────────────────────────────────
    button_y = card_y + 320 if show_forgot_password else card_y + 280
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": input_x,
        "y": button_y,
        "w": input_w,
        "h": 48,
        "fill": primary_color,
        "stroke": "none",
        "rx": 6,
        "label": "Sign In Button"
    })
    
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": input_x,
        "y": button_y + 12,
        "w": input_w,
        "h": 24,
        "text": "Sign In",
        "fontSize": 18,
        "fill": "#e6e9ef",
        "label": "Sign In Button Text"
    })
    
    # ─────────────────────────────────────────────────────────────
    # Social login buttons (if enabled)
    # ─────────────────────────────────────────────────────────────
    if show_social_login:
        social_y = button_y + 70
        
        # Divider
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "text",
            "x": input_x,
            "y": social_y,
            "w": input_w,
            "h": 18,
            "text": "Or continue with",
            "fontSize": 12,
            "fill": "#8b94a7",
            "label": "Social Divider Text"
        })
        
        # Google button
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "rect",
            "x": input_x,
            "y": social_y + 30,
            "w": (input_w - 10) / 2,
            "h": 40,
            "fill": "#ffffff",
            "stroke": "#d0d8e8",
            "rx": 6,
            "label": "Google Button"
        })
        
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "text",
            "x": input_x,
            "y": social_y + 37,
            "w": (input_w - 10) / 2,
            "h": 18,
            "text": "Google",
            "fontSize": 14,
            "fill": "#1b1f2a",
            "label": "Google Button Text"
        })
        
        # GitHub button
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "rect",
            "x": input_x + (input_w - 10) / 2 + 10,
            "y": social_y + 30,
            "w": (input_w - 10) / 2,
            "h": 40,
            "fill": "#ffffff",
            "stroke": "#d0d8e8",
            "rx": 6,
            "label": "GitHub Button"
        })
        
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "text",
            "x": input_x + (input_w - 10) / 2 + 10,
            "y": social_y + 37,
            "w": (input_w - 10) / 2,
            "h": 18,
            "text": "GitHub",
            "fontSize": 14,
            "fill": "#1b1f2a",
            "label": "GitHub Button Text"
        })
    
    # ─────────────────────────────────────────────────────────────
    # Sign up link (if enabled)
    # ─────────────────────────────────────────────────────────────
    if show_signup_link:
        signup_y = button_y + (140 if show_social_login else 70)
        
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "text",
            "x": input_x,
            "y": signup_y,
            "w": input_w,
            "h": 20,
            "text": "Don't have an account? Sign up",
            "fontSize": 14,
            "fill": "#1b1f2a",
            "label": "Sign Up Link"
        })
    
    return {
        "elements": elements,
        "summary": f"Mobile login screen for {app_name} with email/password fields, sign-in button, and optional forgot password, social login, and sign-up links."
    }
