"""
Synthesized capability: weather_app_with_city_selector
Multi-city weather dashboard displaying weather for multiple cities simultaneously in a grid layout. Features include: search functionality to add new cities, remove cities from display, persistent city list, temperature unit conversion (C/F/K), heat index calculation with Steadman formula (when temp ≥ 27°C AND humidity ≥ 40%, otherwise uses apparent temperature), weather warnings, and support for up to 6 cities displayed in a 2-column grid. Each city card shows current temperature, feels-like temperature, humidity, wind speed, heat index, weather description, and active warnings.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import json
    import requests
    import uuid
    
    # Preserve existing elements
    existing = args.get("elements", [])
    if isinstance(existing, str):
        try:
            existing = json.loads(existing)
        except:
            existing = []
    
    # Get parameters
    cities_param = args.get("cities", "London")
    if isinstance(cities_param, str):
        cities_list = [c.strip() for c in cities_param.split(",") if c.strip()]
    else:
        cities_list = cities_param if isinstance(cities_param, list) else ["London"]
    
    unit = args.get("unit", "C")  # "C", "F", or "K"
    search_query = args.get("search_query", "")
    action = args.get("action", "")  # "add" or "remove"
    remove_city = args.get("remove_city", "")
    
    # Handle add/remove actions
    if action == "add" and search_query and search_query not in cities_list:
        cities_list.append(search_query)
    elif action == "remove" and remove_city in cities_list:
        cities_list.remove(remove_city)
    
    # Limit to 6 cities for display
    cities_list = cities_list[:6]
    
    # Fetch weather for all cities
    cities_weather = []
    
    for city in cities_list:
        try:
            # 1. Geocode city
            geo_resp = requests.get(
                f"https://geocoding-api.open-meteo.com/v1/search?name={city}&count=1",
                timeout=20
            )
            geo_data = geo_resp.json()
            if not geo_data.get("results"):
                continue
            
            result = geo_data["results"][0]
            lat = result["latitude"]
            lon = result["longitude"]
            display_city = result.get("name", city)
            country = result.get("country", "")
            
            # 2. Fetch current weather
            weather_url = (
                f"https://api.open-meteo.com/v1/forecast?"
                f"latitude={lat}&longitude={lon}"
                f"&current=temperature_2m,relative_humidity_2m,wind_speed_10m,"
                f"weather_code,apparent_temperature,is_day"
                f"&wind_speed_unit=kmh&timezone=auto"
            )
            weather_resp = requests.get(weather_url, timeout=20)
            weather_data = weather_resp.json()
            current = weather_data["current"]
            
            temp_c = current["temperature_2m"]
            feels_c = current["apparent_temperature"]
            humidity = current["relative_humidity_2m"]
            wind_kmh = current["wind_speed_10m"]
            weather_code = current["weather_code"]
            
            # 3. Convert temperature
            if unit == "F":
                temp_disp = f"{temp_c * 9/5 + 32:.1f}°F"
                feels_disp = f"{feels_c * 9/5 + 32:.1f}°F"
            elif unit == "K":
                temp_disp = f"{temp_c + 273.15:.1f}K"
                feels_disp = f"{feels_c + 273.15:.1f}K"
            else:
                temp_disp = f"{temp_c:.1f}°C"
                feels_disp = f"{feels_c:.1f}°C"
            
            # 4. Calculate heat index
            use_full_calculation = temp_c >= 27 and humidity >= 40
            
            if use_full_calculation:
                hi_c = -8.78469475556 + 1.61139411 * temp_c + 2.33854883889 * humidity - 0.14611605 * temp_c * humidity - 0.22475541 * humidity * humidity + 0.00685182 * temp_c * temp_c * humidity + 0.00000328 * temp_c * humidity * humidity + 0.00000003 * temp_c * temp_c * humidity * humidity - 0.00000003 * humidity * humidity * humidity
                hi_c = max(hi_c, temp_c)
                hi_method = "Steadman"
            else:
                hi_c = feels_c
                hi_method = "Apparent"
            
            if unit == "F":
                hi_disp = f"{hi_c * 9/5 + 32:.1f}°F"
            elif unit == "K":
                hi_disp = f"{hi_c + 273.15:.1f}K"
            else:
                hi_disp = f"{hi_c:.1f}°C"
            
            # 5. Determine warnings
            warnings = []
            if hi_c > 32:
                warnings.append("Extreme heat")
            if humidity > 80:
                warnings.append("High humidity")
            if wind_kmh > 40:
                warnings.append("Strong winds")
            
            # Weather description
            weather_desc = {
                0: "Clear", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
                45: "Foggy", 48: "Rime fog", 51: "Light drizzle", 53: "Moderate drizzle",
                55: "Dense drizzle", 61: "Slight rain", 63: "Moderate rain", 65: "Heavy rain",
                71: "Slight snow", 73: "Moderate snow", 75: "Heavy snow", 77: "Snow grains",
                80: "Rain showers", 81: "Moderate showers", 82: "Violent showers",
                85: "Snow showers", 86: "Heavy snow showers", 95: "Thunderstorm",
                96: "Thunderstorm+hail", 99: "Thunderstorm+hail"
            }.get(weather_code, "Unknown")
            
            cities_weather.append({
                "city": display_city,
                "country": country,
                "temp": temp_disp,
                "feels": feels_disp,
                "humidity": humidity,
                "wind": wind_kmh,
                "hi": hi_disp,
                "hi_method": hi_method,
                "weather": weather_desc,
                "warnings": warnings,
                "original_name": city
            })
        except Exception as e:
            continue
    
    # Build canvas elements
    elements = []
    
    # Background
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "rect",
        "x": 0,
        "y": 0,
        "w": 1400,
        "h": 900,
        "fill": "#f8f9fc",
        "stroke": "none",
        "label": "Canvas background"
    })
    
    # Header
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": 40,
        "y": 20,
        "w": 600,
        "h": 40,
        "text": "Multi-City Weather Dashboard",
        "fontSize": 32,
        "fill": "#1b1f2a",
        "label": "Header"
    })
    
    # Search hint
    elements.append({
        "id": str(uuid.uuid4()),
        "type": "text",
        "x": 40,
        "y": 65,
        "w": 1320,
        "h": 20,
        "text": f"Current cities: {', '.join(cities_list)} | Ask to add/remove cities | Unit: {unit}",
        "fontSize": 13,
        "fill": "#8b94a7",
        "label": "Search hint"
    })
    
    # Grid layout for cities (2 columns, 3 rows max)
    if not cities_weather:
        elements.append({
            "id": str(uuid.uuid4()),
            "type": "text",
            "x": 40,
            "y": 150,
            "w": 1320,
            "h": 40,
            "text": "No cities found. Try searching for a city.",
            "fontSize": 18,
            "fill": "#8b94a7",
            "label": "No data message"
        })
    else:
        card_width = 620
        card_height = 240
        col_spacing = 40
        row_spacing = 30
        start_x = 40
        start_y = 110
        
        for idx, city_data in enumerate(cities_weather):
            col = idx % 2
            row = idx // 2
            
            card_x = start_x + col * (card_width + col_spacing)
            card_y = start_y + row * (card_height + row_spacing)
            
            # Card background
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "rect",
                "x": card_x,
                "y": card_y,
                "w": card_width,
                "h": card_height,
                "fill": "#ffffff",
                "stroke": "#6c8cff",
                "rx": 12,
                "label": f"Card {idx+1}"
            })
            
            # City name and country
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 15,
                "y": card_y + 12,
                "w": 500,
                "h": 28,
                "text": f"{city_data['city']}, {city_data['country']}",
                "fontSize": 20,
                "fill": "#1b1f2a",
                "label": f"City name {idx+1}"
            })
            
            # Remove button (X)
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "rect",
                "x": card_x + card_width - 35,
                "y": card_y + 12,
                "w": 25,
                "h": 25,
                "fill": "#ff6b6b",
                "rx": 4,
                "label": f"Remove btn {idx+1}"
            })
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + card_width - 35,
                "y": card_y + 12,
                "w": 25,
                "h": 25,
                "text": "✕",
                "fontSize": 16,
                "fill": "#ffffff",
                "label": f"Remove icon {idx+1}"
            })
            
            # Weather description
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 15,
                "y": card_y + 45,
                "w": 400,
                "h": 20,
                "text": city_data["weather"],
                "fontSize": 14,
                "fill": "#8b94a7",
                "label": f"Weather desc {idx+1}"
            })
            
            # Temperature (large)
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 15,
                "y": card_y + 70,
                "w": 200,
                "h": 50,
                "text": city_data["temp"],
                "fontSize": 44,
                "fill": "#6c8cff",
                "label": f"Temp {idx+1}"
            })
            
            # Feels like
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 15,
                "y": card_y + 125,
                "w": 300,
                "h": 18,
                "text": f"Feels: {city_data['feels']}",
                "fontSize": 13,
                "fill": "#1b1f2a",
                "label": f"Feels {idx+1}"
            })
            
            # Heat index (right side)
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "rect",
                "x": card_x + 320,
                "y": card_y + 70,
                "w": 280,
                "h": 75,
                "fill": "#fff5e6",
                "stroke": "#ffb454",
                "rx": 8,
                "label": f"HI box {idx+1}"
            })
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 330,
                "y": card_y + 78,
                "w": 260,
                "h": 16,
                "text": "Heat Index",
                "fontSize": 12,
                "fill": "#1b1f2a",
                "label": f"HI label {idx+1}"
            })
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 330,
                "y": card_y + 98,
                "w": 260,
                "h": 35,
                "text": city_data["hi"],
                "fontSize": 32,
                "fill": "#ffb454",
                "label": f"HI value {idx+1}"
            })
            
            # Details row
            details_y = card_y + 155
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 15,
                "y": details_y,
                "w": 80,
                "h": 16,
                "text": f"Humidity",
                "fontSize": 12,
                "fill": "#8b94a7",
                "label": f"Humidity label {idx+1}"
            })
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 15,
                "y": details_y + 18,
                "w": 80,
                "h": 22,
                "text": f"{city_data['humidity']}%",
                "fontSize": 18,
                "fill": "#1b1f2a",
                "label": f"Humidity value {idx+1}"
            })
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 120,
                "y": details_y,
                "w": 80,
                "h": 16,
                "text": f"Wind",
                "fontSize": 12,
                "fill": "#8b94a7",
                "label": f"Wind label {idx+1}"
            })
            
            elements.append({
                "id": str(uuid.uuid4()),
                "type": "text",
                "x": card_x + 120,
                "y": details_y + 18,
                "w": 80,
                "h": 22,
                "text": f"{city_data['wind']:.1f}",
                "fontSize": 18,
                "fill": "#1b1f2a",
                "label": f"Wind value {idx+1}"
            })
            
            # Warnings
            if city_data["warnings"]:
                warn_text = " | ".join(city_data["warnings"])
                elements.append({
                    "id": str(uuid.uuid4()),
                    "type": "text",
                    "x": card_x + 320,
                    "y": details_y,
                    "w": 280,
                    "h": 40,
                    "text": f"⚠️ {warn_text}",
                    "fontSize": 11,
                    "fill": "#d32f2f",
                    "label": f"Warnings {idx+1}"
                })
    
    # Summary
    summary_text = f"Showing {len(cities_weather)} cities: " + ", ".join([c["city"] for c in cities_weather])
    
    return {
        "elements": elements,
        "summary": summary_text,
        "cities": cities_list
    }
