"""
Synthesized capability: visualize_quick_sort
Executes quick sort step-by-step on an input array and renders each comparison, swap, and partition as an animation frame.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import io
    import base64
    
    # Read input or create default
    data = args.get('data', [64, 34, 25, 12, 22, 11, 90, 88])
    if not data:
        data = [64, 34, 25, 12, 22, 11, 90, 88]
    
    data = list(data)  # ensure it's a list
    frames = []
    step_count = [0]  # mutable counter
    
    # Capture state: (array_copy, compared_indices, swapped_indices, sorted_indices, step_label)
    states = []
    
    def capture_state(arr, compared=None, swapped=None, sorted_set=None, label=""):
        """Record a snapshot of the array state."""
        compared = compared or []
        swapped = swapped or []
        sorted_set = sorted_set or set()
        states.append({
            'array': list(arr),
            'compared': compared,
            'swapped': swapped,
            'sorted': sorted_set,
            'label': label
        })
    
    def partition(arr, low, high, states_list):
        """Partition for quicksort; capture states during partitioning."""
        pivot = arr[high]
        i = low - 1
        
        for j in range(low, high):
            # Capture comparison
            states_list.append({
                'array': list(arr),
                'compared': [j, high],
                'swapped': [],
                'sorted': set(),
                'label': f"Compare arr[{j}]={arr[j]} with pivot={pivot}"
            })
            
            if arr[j] < pivot:
                i += 1
                # Capture swap
                arr[i], arr[j] = arr[j], arr[i]
                states_list.append({
                    'array': list(arr),
                    'compared': [],
                    'swapped': [i, j],
                    'sorted': set(),
                    'label': f"Swap arr[{i}] and arr[{j}]"
                })
        
        # Final pivot placement
        arr[i + 1], arr[high] = arr[high], arr[i + 1]
        states_list.append({
            'array': list(arr),
            'compared': [],
            'swapped': [i + 1, high],
            'sorted': set(),
            'label': f"Place pivot at index {i + 1}"
        })
        
        return i + 1
    
    def quicksort(arr, low, high, states_list):
        """Quicksort with state capture."""
        if low < high:
            pi = partition(arr, low, high, states_list)
            quicksort(arr, low, pi - 1, states_list)
            quicksort(arr, pi + 1, high, states_list)
    
    # Initial state
    states.append({
        'array': list(data),
        'compared': [],
        'swapped': [],
        'sorted': set(),
        'label': "Initial array"
    })
    
    # Run quicksort
    quicksort(data, 0, len(data) - 1, states)
    
    # Final state
    states.append({
        'array': list(data),
        'compared': [],
        'swapped': [],
        'sorted': set(range(len(data))),
        'label': "Sorted!"
    })
    
    # Limit frames to ~60
    stride = max(1, len(states) // 60)
    states = states[::stride]
    
    # Render each state as a frame
    for state in states:
        fig, ax = plt.subplots(figsize=(7, 4), dpi=100)
        
        arr = state['array']
        compared = state['compared']
        swapped = state['swapped']
        sorted_set = state['sorted']
        label = state['label']
        
        # Color each bar
        colors = []
        for i in range(len(arr)):
            if i in sorted_set:
                colors.append('green')
            elif i in swapped:
                colors.append('red')
            elif i in compared:
                colors.append('orange')
            else:
                colors.append('steelblue')
        
        # Draw bars
        bars = ax.bar(range(len(arr)), arr, color=colors, edgecolor='black', linewidth=1.5)
        
        ax.set_xlabel('Index', fontsize=10)
        ax.set_ylabel('Value', fontsize=10)
        ax.set_title(f"Quick Sort: {label}", fontsize=11, fontweight='bold')
        ax.set_ylim(0, max(arr) * 1.1 if arr else 100)
        ax.grid(axis='y', alpha=0.3)
        
        # Legend
        legend_elements = [
            mpatches.Patch(facecolor='steelblue', edgecolor='black', label='Unsorted'),
            mpatches.Patch(facecolor='orange', edgecolor='black', label='Compared'),
            mpatches.Patch(facecolor='red', edgecolor='black', label='Swapped'),
            mpatches.Patch(facecolor='green', edgecolor='black', label='Sorted'),
        ]
        ax.legend(handles=legend_elements, loc='upper right', fontsize=9)
        
        # Save to base64
        buf = io.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
        buf.seek(0)
        frame_b64 = base64.b64encode(buf.read()).decode('utf-8')
        frames.append(frame_b64)
        
        plt.close(fig)
    
    return {
        'frames': frames,
        'step_count': len(states),
        'algorithm': 'Quick Sort',
        'input': list(args.get('data', [64, 34, 25, 12, 22, 11, 90, 88])),
        'explanation_hint': 'Blue=unsorted, Orange=compared, Red=swapped, Green=sorted'
    }
