"""
Synthesized capability: visualize_backpropagation
Executes backpropagation step-by-step on a neural network and renders each phase (forward pass, backward deltas, weight updates) as animation frames.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
    import io
    import base64
    
    # ─────────────────────────────────────────────────────────────────
    # Parse input: a simple neural network with weights and biases
    # ─────────────────────────────────────────────────────────────────
    
    # Default: a tiny 2-layer network (2 inputs → 3 hidden → 1 output)
    network = args.get('network', {
        'layers': [
            {'weights': [[0.5, -0.3], [0.2, 0.8], [-0.1, 0.6]], 'bias': [0.1, -0.2, 0.3]},
            {'weights': [[0.4, -0.5, 0.2]], 'bias': [0.05]}
        ]
    })
    
    x_input = args.get('input', np.array([1.0, 0.5]))
    y_target = args.get('target', np.array([0.8]))
    learning_rate = args.get('learning_rate', 0.1)
    
    # Convert to numpy arrays
    x_input = np.array(x_input, dtype=float)
    y_target = np.array(y_target, dtype=float)
    
    # ─────────────────────────────────────────────────────────────────
    # Initialize network state
    # ─────────────────────────────────────────────────────────────────
    
    layers = []
    for layer_def in network['layers']:
        layer = {
            'weights': np.array(layer_def['weights'], dtype=float),
            'bias': np.array(layer_def['bias'], dtype=float),
            'z': None,  # pre-activation
            'a': None,  # post-activation
            'delta': None,  # gradient w.r.t. z
        }
        layers.append(layer)
    
    frames = []
    step_log = []
    
    # ─────────────────────────────────────────────────────────────────
    # FORWARD PASS
    # ─────────────────────────────────────────────────────────────────
    
    a = x_input
    for i, layer in enumerate(layers):
        z = np.dot(layer['weights'], a) + layer['bias']
        a = 1.0 / (1.0 + np.exp(-np.clip(z, -500, 500)))  # sigmoid
        layer['z'] = z
        layer['a'] = a
        step_log.append(f"Forward: Layer {i+1} → z={z}, a={a}")
    
    y_pred = a
    loss = 0.5 * np.sum((y_pred - y_target) ** 2)
    step_log.append(f"Loss: {loss:.4f}")
    
    # Render forward pass frame
    fig = _render_network_state(layers, x_input, y_target, y_pred, 
                                 "Forward Pass", step_log[-1])
    frames.append(_fig_to_base64(fig))
    plt.close(fig)
    
    # ─────────────────────────────────────────────────────────────────
    # BACKWARD PASS
    # ─────────────────────────────────────────────────────────────────
    
    # Output layer gradient
    delta = (y_pred - y_target) * y_pred * (1 - y_pred)  # sigmoid derivative
    layers[-1]['delta'] = delta
    step_log.append(f"Backprop: Output layer delta={delta}")
    
    fig = _render_network_state(layers, x_input, y_target, y_pred,
                                 "Backprop: Output Layer", step_log[-1])
    frames.append(_fig_to_base64(fig))
    plt.close(fig)
    
    # Hidden layers
    for i in range(len(layers) - 2, -1, -1):
        # Propagate delta backward
        delta = np.dot(layers[i+1]['weights'].T, delta) * layers[i]['a'] * (1 - layers[i]['a'])
        layers[i]['delta'] = delta
        step_log.append(f"Backprop: Layer {i+1} delta={delta}")
        
        fig = _render_network_state(layers, x_input, y_target, y_pred,
                                     f"Backprop: Layer {i+1}", step_log[-1])
        frames.append(_fig_to_base64(fig))
        plt.close(fig)
    
    # ─────────────────────────────────────────────────────────────────
    # WEIGHT UPDATE
    # ─────────────────────────────────────────────────────────────────
    
    a = x_input
    for i, layer in enumerate(layers):
        # Gradient w.r.t. weights: delta ⊗ a_prev
        dW = np.outer(layer['delta'], a)
        db = layer['delta']
        
        # Update
        layer['weights'] -= learning_rate * dW
        layer['bias'] -= learning_rate * db
        
        step_log.append(f"Update: Layer {i+1} weights & bias")
        
        fig = _render_network_state(layers, x_input, y_target, y_pred,
                                     f"Weight Update: Layer {i+1}", step_log[-1])
        frames.append(_fig_to_base64(fig))
        plt.close(fig)
        
        a = layer['a']
    
    # ─────────────────────────────────────────────────────────────────
    # Return result
    # ─────────────────────────────────────────────────────────────────
    
    return {
        'frames': frames,
        'step_count': len(frames),
        'algorithm': 'Backpropagation',
        'input': x_input.tolist(),
        'target': y_target.tolist(),
        'final_loss': float(loss),
        'explanation_hint': 'Blue=input, Green=hidden activations, Red=output; arrows show weight flow; deltas propagate backward.'
    }


def _render_network_state(layers, x_input, y_target, y_pred, title, subtitle):
    """Render a neural network diagram with current activations and deltas."""
    fig, ax = plt.subplots(figsize=(7, 4), dpi=100)
    ax.set_xlim(-0.5, len(layers) + 1.5)
    ax.set_ylim(-0.5, 4)
    ax.axis('off')
    
    # Layer positions
    layer_x = [0] + list(range(1, len(layers) + 1))
    
    # Draw input nodes
    for j, val in enumerate(x_input):
        y_pos = 2 - j * 0.8
        circle = plt.Circle((layer_x[0], y_pos), 0.25, color='blue', alpha=0.7)
        ax.add_patch(circle)
        ax.text(layer_x[0], y_pos, f'{val:.2f}', ha='center', va='center', 
                fontsize=8, color='white', weight='bold')
    
    # Draw hidden and output nodes
    for i, layer in enumerate(layers):
        a = layer['a']
        delta = layer['delta']
        for j, (activation, grad) in enumerate(zip(a, delta if delta is not None else [None]*len(a))):
            y_pos = 2 - j * 0.8
            
            # Color: green for activation, red tint if delta is large
            if grad is not None:
                intensity = min(abs(grad), 1.0)
                color = (1.0, 1.0 - intensity, 1.0 - intensity)  # red tint
            else:
                color = 'green'
            
            circle = plt.Circle((layer_x[i+1], y_pos), 0.25, color=color, alpha=0.7)
            ax.add_patch(circle)
            ax.text(layer_x[i+1], y_pos, f'{activation:.2f}', ha='center', va='center',
                    fontsize=8, color='white', weight='bold')
    
    # Draw connections (simplified)
    for i in range(len(layers)):
        n_prev = len(x_input) if i == 0 else len(layers[i-1]['a'])
        n_curr = len(layers[i]['a'])
        for j in range(min(n_prev, 2)):  # Draw only first 2 connections to avoid clutter
            y_prev = 2 - j * 0.8
            for k in range(min(n_curr, 2)):
                y_curr = 2 - k * 0.8
                ax.plot([layer_x[i] + 0.25, layer_x[i+1] - 0.25],
                       [y_prev, y_curr], 'gray', alpha=0.3, linewidth=0.5)
    
    ax.text(0.5, 3.5, title, fontsize=12, weight='bold')
    ax.text(0.5, 3.2, subtitle, fontsize=9, style='italic', color='gray')
    ax.text(0.5, -0.3, f'Target: {y_target[0]:.2f} | Pred: {y_pred[0]:.2f}',
            fontsize=9, color='darkblue')
    
    return fig


def _fig_to_base64(fig):
    """Convert matplotlib figure to base64 PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode('utf-8')
