"""
Synthesized capability: visualize_q_learning
Run Q-learning on a grid world step-by-step and render each episode as an animation frame showing the learned value function.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import numpy as np
    import io
    import base64
    
    # ─────────────────────────────────────────────────────────────────
    # Parse input: grid size, discount factor, learning rate, episodes
    # ─────────────────────────────────────────────────────────────────
    grid_size = args.get('grid_size', 5)
    discount_factor = args.get('discount_factor', 0.9)
    learning_rate = args.get('learning_rate', 0.1)
    episodes = args.get('episodes', 10)
    max_steps_per_episode = args.get('max_steps_per_episode', 20)
    
    # Create a simple grid world: agent starts at (0,0), goal at (grid_size-1, grid_size-1)
    start_pos = (0, 0)
    goal_pos = (grid_size - 1, grid_size - 1)
    
    # Initialize Q-table: Q[state][action] where state=(x,y), action in [0,1,2,3]
    # Actions: 0=up, 1=right, 2=down, 3=left
    Q = {}
    for x in range(grid_size):
        for y in range(grid_size):
            Q[(x, y)] = [0.0, 0.0, 0.0, 0.0]
    
    frames = []
    step_log = []
    
    def get_next_pos(pos, action):
        """Return next position given action. Clamp to grid bounds."""
        x, y = pos
        if action == 0:  # up
            x = max(0, x - 1)
        elif action == 1:  # right
            y = min(grid_size - 1, y + 1)
        elif action == 2:  # down
            x = min(grid_size - 1, x + 1)
        elif action == 3:  # left
            y = max(0, y - 1)
        return (x, y)
    
    def get_reward(pos):
        """Reward: +1 at goal, -0.01 elsewhere (small penalty for steps)."""
        if pos == goal_pos:
            return 1.0
        return -0.01
    
    def render_frame(episode, step, current_pos, Q_table, title_suffix=""):
        """Render current Q-learning state as a heatmap + agent position."""
        fig, ax = plt.subplots(figsize=(7, 4), dpi=100)
        
        # Compute max Q-value at each state for heatmap
        heatmap = np.zeros((grid_size, grid_size))
        for x in range(grid_size):
            for y in range(grid_size):
                heatmap[x, y] = max(Q_table[(x, y)])
        
        # Draw heatmap
        im = ax.imshow(heatmap, cmap='YlOrRd', origin='upper', vmin=0, vmax=1)
        
        # Draw grid
        for i in range(grid_size + 1):
            ax.axhline(i - 0.5, color='gray', linewidth=0.5)
            ax.axvline(i - 0.5, color='gray', linewidth=0.5)
        
        # Mark start, goal, and current position
        ax.plot(start_pos[1], start_pos[0], 'g*', markersize=20, label='Start')
        ax.plot(goal_pos[1], goal_pos[0], 'b*', markersize=20, label='Goal')
        ax.plot(current_pos[1], current_pos[0], 'ro', markersize=15, label='Agent')
        
        ax.set_xticks(range(grid_size))
        ax.set_yticks(range(grid_size))
        ax.set_xticklabels(range(grid_size))
        ax.set_yticklabels(range(grid_size))
        ax.legend(loc='upper right', fontsize=8)
        ax.set_title(f'Q-Learning: Episode {episode}, Step {step} {title_suffix}', fontsize=10)
        
        # Colorbar
        plt.colorbar(im, ax=ax, label='Max Q-value')
        
        # Convert to base64
        buf = io.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
        buf.seek(0)
        img_base64 = base64.b64encode(buf.read()).decode('utf-8')
        plt.close(fig)
        
        return img_base64
    
    # ─────────────────────────────────────────────────────────────────
    # Q-Learning training loop
    # ─────────────────────────────────────────────────────────────────
    total_steps = 0
    max_frames = 60
    frame_stride = max(1, (episodes * max_steps_per_episode) // max_frames)
    
    for episode in range(episodes):
        pos = start_pos
        
        # Render initial state of episode
        if total_steps % frame_stride == 0:
            frames.append(render_frame(episode, 0, pos, Q, "(start)"))
        
        for step in range(max_steps_per_episode):
            total_steps += 1
            
            # ε-greedy action selection (ε decreases over time)
            epsilon = max(0.01, 1.0 - episode / episodes)
            if np.random.random() < epsilon:
                action = np.random.randint(0, 4)
            else:
                action = np.argmax(Q[pos])
            
            # Take action
            next_pos = get_next_pos(pos, action)
            reward = get_reward(next_pos)
            
            # Q-learning update
            old_q = Q[pos][action]
            max_next_q = max(Q[next_pos])
            Q[pos][action] = old_q + learning_rate * (reward + discount_factor * max_next_q - old_q)
            
            step_log.append({
                'episode': episode,
                'step': step,
                'pos': pos,
                'action': action,
                'next_pos': next_pos,
                'reward': reward,
                'q_value': Q[pos][action]
            })
            
            # Render frame
            if total_steps % frame_stride == 0:
                frames.append(render_frame(episode, step + 1, next_pos, Q, f"(r={reward:.2f})"))
            
            pos = next_pos
            
            # Stop if goal reached
            if pos == goal_pos:
                break
    
    # Ensure at least one frame
    if not frames:
        frames.append(render_frame(episodes - 1, max_steps_per_episode, goal_pos, Q, "(final)"))
    
    return {
        "frames": frames,
        "step_count": len(step_log),
        "algorithm": "Q-Learning",
        "input": {
            "grid_size": grid_size,
            "start": start_pos,
            "goal": goal_pos,
            "episodes": episodes,
            "learning_rate": learning_rate,
            "discount_factor": discount_factor
        },
        "explanation_hint": "Red heatmap shows max Q-value at each state (higher = better). Green star = start, blue star = goal, red circle = agent. Darker red = agent has learned this state is valuable."
    }
