"""
Synthesized capability: visualize_breadth_first_search
Executes breadth-first search on a graph step-by-step and renders each step as an animation frame showing node colors and queue state.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
    import io
    import base64
    from collections import deque
    
    # Read input graph from args, or create a sensible example
    graph = args.get('graph', None)
    start_node = args.get('start_node', 0)
    
    if graph is None:
        # Create a small example graph (adjacency list)
        graph = {
            0: [1, 2],
            1: [0, 3, 4],
            2: [0, 5],
            3: [1],
            4: [1, 5],
            5: [2, 4]
        }
    
    # Validate start_node
    if start_node not in graph:
        start_node = list(graph.keys())[0] if graph else 0
    
    # Run BFS step-by-step, capturing state after each meaningful step
    frames = []
    visited = set()
    queue = deque([start_node])
    visited.add(start_node)
    step_count = 0
    
    # Track state for rendering: (visited_set, queue_list, current_node, frontier_nodes)
    states = []
    states.append({
        'visited': visited.copy(),
        'queue': list(queue),
        'current': start_node,
        'frontier': set(queue),
        'step': 0,
        'action': f'Initialize: start at node {start_node}'
    })
    
    while queue:
        current = queue.popleft()
        step_count += 1
        
        # Record state after dequeuing
        states.append({
            'visited': visited.copy(),
            'queue': list(queue),
            'current': current,
            'frontier': set(queue),
            'step': step_count,
            'action': f'Dequeue node {current}'
        })
        
        # Explore neighbors
        for neighbor in sorted(graph.get(current, [])):
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)
                step_count += 1
                
                # Record state after enqueueing a new neighbor
                states.append({
                    'visited': visited.copy(),
                    'queue': list(queue),
                    'current': current,
                    'frontier': set(queue),
                    'step': step_count,
                    'action': f'Visit neighbor {neighbor} from {current}'
                })
    
    # Add final state
    states.append({
        'visited': visited.copy(),
        'queue': [],
        'current': None,
        'frontier': set(),
        'step': step_count + 1,
        'action': 'BFS complete'
    })
    
    # Limit frames to 60
    stride = max(1, len(states) // 60)
    states = states[::stride]
    
    # Render each state as a frame
    for state in states:
        fig, ax = plt.subplots(figsize=(7, 4), dpi=100)
        
        # Simple circular layout for nodes
        import math
        num_nodes = len(graph)
        radius = 1.5
        positions = {}
        for i, node in enumerate(sorted(graph.keys())):
            angle = 2 * math.pi * i / num_nodes
            positions[node] = (radius * math.cos(angle), radius * math.sin(angle))
        
        # Draw edges
        for node in graph:
            for neighbor in graph[node]:
                if node < neighbor:  # Draw each edge once
                    x1, y1 = positions[node]
                    x2, y2 = positions[neighbor]
                    ax.plot([x1, x2], [y1, y2], 'k-', alpha=0.3, linewidth=1)
        
        # Draw nodes with colors based on state
        visited_set = state['visited']
        frontier_set = state['frontier']
        current_node = state['current']
        
        for node in sorted(graph.keys()):
            x, y = positions[node]
            
            # Determine color
            if node == current_node:
                color = 'red'  # Currently processing
            elif node in frontier_set:
                color = 'orange'  # In queue (frontier)
            elif node in visited_set:
                color = 'lightgreen'  # Already visited
            else:
                color = 'lightgray'  # Not yet visited
            
            circle = plt.Circle((x, y), 0.3, color=color, ec='black', linewidth=2, zorder=3)
            ax.add_patch(circle)
            ax.text(x, y, str(node), ha='center', va='center', fontsize=12, fontweight='bold', zorder=4)
        
        ax.set_xlim(-2.5, 2.5)
        ax.set_ylim(-2.5, 2.5)
        ax.set_aspect('equal')
        ax.axis('off')
        
        # Title and legend
        ax.set_title(f"BFS Step {state['step']}: {state['action']}", fontsize=12, fontweight='bold')
        
        # Legend
        red_patch = mpatches.Patch(color='red', label='Current')
        orange_patch = mpatches.Patch(color='orange', label='Frontier (Queue)')
        green_patch = mpatches.Patch(color='lightgreen', label='Visited')
        gray_patch = mpatches.Patch(color='lightgray', label='Unvisited')
        ax.legend(handles=[red_patch, orange_patch, green_patch, gray_patch],
                  loc='upper right', fontsize=9)
        
        # Render to base64
        buf = io.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
        buf.seek(0)
        frame_b64 = base64.b64encode(buf.read()).decode('utf-8')
        frames.append(frame_b64)
        plt.close(fig)
    
    return {
        'frames': frames,
        'step_count': len(states),
        'algorithm': 'Breadth-First Search (BFS)',
        'input': {
            'graph': graph,
            'start_node': start_node
        },
        'explanation_hint': 'Red = current node being processed; Orange = frontier (queued); Green = visited; Gray = unvisited'
    }
