"""
Synthesized capability: visualize_gradient_descent
Runs gradient descent optimization step-by-step on a 2D quadratic loss function and renders each iteration as a contour plot with trajectory.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import numpy as np
    import io
    import base64
    
    # Read input parameters
    learning_rate = args.get('learning_rate', 0.01)
    iterations = args.get('iterations', 50)
    initial_x = args.get('initial_x', 5.0)
    initial_y = args.get('initial_y', 5.0)
    
    # Define a simple quadratic loss function: f(x, y) = (x-1)^2 + (y-2)^2
    # Gradient: df/dx = 2(x-1), df/dy = 2(y-2)
    def loss_function(x, y):
        return (x - 1)**2 + (y - 2)**2
    
    def gradient(x, y):
        grad_x = 2 * (x - 1)
        grad_y = 2 * (y - 2)
        return grad_x, grad_y
    
    # Initialize
    x, y = initial_x, initial_y
    frames = []
    history = [(x, y, loss_function(x, y))]
    
    # Run gradient descent with step capture
    for step in range(iterations):
        grad_x, grad_y = gradient(x, y)
        x = x - learning_rate * grad_x
        y = y - learning_rate * grad_y
        loss = loss_function(x, y)
        history.append((x, y, loss))
    
    # Sample frames if too many (keep first, last, and evenly spaced)
    if len(history) > 60:
        indices = set([0, len(history) - 1])
        stride = len(history) // 58
        indices.update(range(0, len(history), stride))
        indices = sorted(list(indices))
        sampled_history = [history[i] for i in indices]
    else:
        sampled_history = history
    
    # Create contour plot background (loss landscape)
    x_range = np.linspace(-2, 8, 100)
    y_range = np.linspace(-2, 8, 100)
    X, Y = np.meshgrid(x_range, y_range)
    Z = (X - 1)**2 + (Y - 2)**2
    
    # Render each frame
    for frame_idx, (curr_x, curr_y, curr_loss) in enumerate(sampled_history):
        fig, ax = plt.subplots(figsize=(7, 4), dpi=100)
        
        # Draw contour plot
        contour = ax.contour(X, Y, Z, levels=15, cmap='viridis', alpha=0.6)
        ax.clabel(contour, inline=True, fontsize=8)
        
        # Draw trajectory so far
        hist_x = [h[0] for h in sampled_history[:frame_idx + 1]]
        hist_y = [h[1] for h in sampled_history[:frame_idx + 1]]
        ax.plot(hist_x, hist_y, 'r-', linewidth=2, alpha=0.7, label='Trajectory')
        
        # Draw current point
        ax.plot(curr_x, curr_y, 'ro', markersize=10, label='Current position', zorder=5)
        
        # Draw optimum
        ax.plot(1, 2, 'g*', markersize=20, label='Optimum (1, 2)', zorder=5)
        
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_title(f'Gradient Descent Step {frame_idx} | Loss: {curr_loss:.4f}')
        ax.legend(loc='upper right', fontsize=9)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(-2, 8)
        ax.set_ylim(-2, 8)
        
        # Render to base64
        buf = io.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
        buf.seek(0)
        frame_b64 = base64.b64encode(buf.read()).decode('utf-8')
        frames.append(frame_b64)
        plt.close(fig)
        buf.close()
    
    return {
        "frames": frames,
        "step_count": len(sampled_history),
        "algorithm": "Gradient Descent",
        "input": {
            "learning_rate": learning_rate,
            "iterations": iterations,
            "initial_x": initial_x,
            "initial_y": initial_y,
            "loss_function": "(x-1)^2 + (y-2)^2"
        },
        "explanation_hint": "Red line shows trajectory, red dot is current position, green star is optimum at (1,2). Contours show loss landscape."
    }
