"""
Synthesized capability: visualize_bubble_sort
Executes bubble sort step-by-step and renders each comparison and swap as an animation frame.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import io
    import base64
    
    # Read input or create default
    data = args.get('data', [64, 34, 25, 12, 22, 11, 90, 88])
    if not data:
        data = [64, 34, 25, 12, 22, 11, 90, 88]
    
    data = list(data)  # ensure it's a list
    n = len(data)
    frames = []
    step_count = 0
    
    # Capture initial state
    def capture_frame(arr, title, compared_indices=None, swapped_indices=None, sorted_indices=None):
        """Render current array state as a bar chart."""
        fig, ax = plt.subplots(figsize=(7, 4), dpi=100)
        
        colors = ['lightblue'] * len(arr)
        
        # Mark sorted region in green
        if sorted_indices:
            for i in sorted_indices:
                colors[i] = 'lightgreen'
        
        # Mark compared indices in orange
        if compared_indices:
            for i in compared_indices:
                colors[i] = 'orange'
        
        # Mark swapped indices in red
        if swapped_indices:
            for i in swapped_indices:
                colors[i] = 'red'
        
        bars = ax.bar(range(len(arr)), arr, color=colors, edgecolor='black', linewidth=1.5)
        ax.set_ylim(0, max(data) * 1.1)
        ax.set_xlabel('Index')
        ax.set_ylabel('Value')
        ax.set_title(title)
        ax.set_xticks(range(len(arr)))
        
        # Add legend
        legend_elements = [
            mpatches.Patch(facecolor='lightblue', edgecolor='black', label='Unsorted'),
            mpatches.Patch(facecolor='orange', edgecolor='black', label='Comparing'),
            mpatches.Patch(facecolor='red', edgecolor='black', label='Swapping'),
            mpatches.Patch(facecolor='lightgreen', edgecolor='black', label='Sorted'),
        ]
        ax.legend(handles=legend_elements, loc='upper right', fontsize=8)
        
        # Save to base64
        buf = io.BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight')
        buf.seek(0)
        img_base64 = base64.b64encode(buf.read()).decode('utf-8')
        frames.append(img_base64)
        plt.close(fig)
        
        return len(frames)
    
    # Initial frame
    step_count = capture_frame(data, f'Bubble Sort: Initial Array', sorted_indices=[])
    
    # Bubble sort with step-by-step capture
    for i in range(n):
        swapped = False
        sorted_region = list(range(n - i, n))  # rightmost i elements are sorted
        
        for j in range(n - i - 1):
            # Capture comparison
            step_count = capture_frame(
                data,
                f'Bubble Sort: Pass {i+1}, Comparing indices {j} and {j+1}',
                compared_indices=[j, j+1],
                sorted_indices=sorted_region
            )
            
            # Perform comparison and swap
            if data[j] > data[j+1]:
                data[j], data[j+1] = data[j+1], data[j]
                swapped = True
                
                # Capture swap
                step_count = capture_frame(
                    data,
                    f'Bubble Sort: Pass {i+1}, Swapped indices {j} and {j+1}',
                    swapped_indices=[j, j+1],
                    sorted_indices=sorted_region
                )
        
        # Update sorted region after each pass
        sorted_region = list(range(n - i - 1, n))
        step_count = capture_frame(
            data,
            f'Bubble Sort: Pass {i+1} Complete',
            sorted_indices=sorted_region
        )
        
        if not swapped:
            break
    
    # Final frame
    step_count = capture_frame(
        data,
        'Bubble Sort: Complete!',
        sorted_indices=list(range(n))
    )
    
    return {
        'frames': frames,
        'step_count': step_count,
        'algorithm': 'Bubble Sort',
        'input': list(args.get('data', [64, 34, 25, 12, 22, 11, 90, 88])),
        'explanation_hint': 'Blue=unsorted, Orange=comparing, Red=swapping, Green=sorted region'
    }
