"""
Synthesized capability: aggregate_table
Aggregates tabular data by a grouping column using a specified function (mean, sum, count, median, min, max) and renders the result as a bar/line/barh chart.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import pandas as pd
    import matplotlib.pyplot as plt
    import io
    import base64
    from collections import defaultdict
    
    # Extract inputs
    rows = args.get('rows', [])
    columns = args.get('columns', [])
    
    # Aggregation parameters
    group_by = args.get('group_by', None)  # e.g., 'department'
    metric = args.get('metric', None)       # e.g., 'salary'
    agg_func = args.get('agg_func', 'mean') # e.g., 'mean', 'sum', 'count', 'median'
    
    # Chart parameters
    chart_kind = args.get('chart_kind', 'bar')  # bar, line, barh, etc.
    title = args.get('title', None)
    x_label = args.get('x_label', group_by or 'Group')
    y_label = args.get('y_label', f'{agg_func.capitalize()} {metric}' if metric else 'Value')
    sort_by = args.get('sort_by', None)  # 'value' or 'key' or None
    sort_order = args.get('sort_order', 'descending')  # 'ascending' or 'descending'
    
    # Validate inputs
    if not rows or not group_by or not metric:
        return {
            'error': 'Missing required parameters: rows, group_by, metric',
            'image_base64': None
        }
    
    if group_by not in columns or metric not in columns:
        return {
            'error': f'Column not found. Available: {columns}',
            'image_base64': None
        }
    
    # Parse and aggregate data
    aggregated = defaultdict(list)
    
    for row in rows:
        group_key = row.get(group_by)
        metric_val = row.get(metric)
        
        if group_key is None or metric_val is None:
            continue
        
        # Clean metric value: remove currency symbols, commas, units
        metric_str = str(metric_val).strip()
        metric_str = metric_str.replace('$', '').replace(',', '').replace('kms', '').strip()
        
        try:
            metric_num = float(metric_str)
            aggregated[str(group_key)].append(metric_num)
        except (ValueError, TypeError):
            continue
    
    if not aggregated:
        return {
            'error': 'No valid data to aggregate',
            'image_base64': None
        }
    
    # Compute aggregation
    result = {}
    for group_key, values in aggregated.items():
        if agg_func == 'mean':
            result[group_key] = sum(values) / len(values)
        elif agg_func == 'sum':
            result[group_key] = sum(values)
        elif agg_func == 'count':
            result[group_key] = len(values)
        elif agg_func == 'median':
            sorted_vals = sorted(values)
            n = len(sorted_vals)
            result[group_key] = sorted_vals[n // 2] if n % 2 == 1 else (sorted_vals[n // 2 - 1] + sorted_vals[n // 2]) / 2
        elif agg_func == 'min':
            result[group_key] = min(values)
        elif agg_func == 'max':
            result[group_key] = max(values)
        else:
            result[group_key] = sum(values) / len(values)  # default to mean
    
    # Sort if requested
    if sort_by == 'value':
        result = dict(sorted(result.items(), key=lambda x: x[1], reverse=(sort_order == 'descending')))
    elif sort_by == 'key':
        result = dict(sorted(result.items(), key=lambda x: x[0], reverse=(sort_order == 'descending')))
    
    # Create chart
    fig, ax = plt.subplots(figsize=(10, 6))
    
    keys = list(result.keys())
    values = list(result.values())
    
    if chart_kind == 'barh':
        ax.barh(keys, values, color='steelblue')
        ax.set_xlabel(y_label)
        ax.set_ylabel(x_label)
    else:  # default to 'bar'
        ax.bar(keys, values, color='steelblue')
        ax.set_xlabel(x_label)
        ax.set_ylabel(y_label)
        plt.xticks(rotation=45, ha='right')
    
    if title:
        ax.set_title(title)
    else:
        ax.set_title(f'{agg_func.capitalize()} {metric} by {group_by}')
    
    plt.tight_layout()
    
    # Encode to base64
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=100, bbox_inches='tight')
    buf.seek(0)
    image_base64 = base64.b64encode(buf.read()).decode('utf-8')
    plt.close(fig)
    
    return {
        'aggregated_data': result,
        'image_base64': image_base64,
        'chart_kind': chart_kind,
        'group_by': group_by,
        'metric': metric,
        'agg_func': agg_func
    }
