"""
Synthesized capability: plot_chart
Render a chart (bar, line, scatter, histogram, etc.) from tabular data with configurable aggregation and grouping.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import pandas as pd
    import matplotlib.pyplot as plt
    import io
    import base64
    from collections import defaultdict
    
    # Extract inputs
    rows = args.get('rows', [])
    columns = args.get('columns', [])
    
    # Chart configuration (general parameters for any chart)
    chart_kind = args.get('kind', 'bar')  # bar, line, scatter, histogram, box, etc.
    x_col = args.get('x', None)
    y_col = args.get('y', None)
    series_col = args.get('series', None)
    agg_func = args.get('agg', 'mean')  # mean, sum, count, median, etc.
    title = args.get('title', None)
    xlabel = args.get('xlabel', None)
    ylabel = args.get('ylabel', None)
    
    # For this specific invocation: default to salary by department
    if not x_col:
        x_col = args.get('group_by', 'department')
    if not y_col:
        y_col = args.get('metric', 'salary')
    if not title:
        title = args.get('title', f'{agg_func.capitalize()} {y_col} by {x_col}')
    if not ylabel:
        ylabel = f'{agg_func.capitalize()} {y_col}'
    if not xlabel:
        xlabel = x_col
    
    # Validate columns exist
    if x_col not in columns or y_col not in columns:
        return {
            'error': f'Column not found. Available: {columns}',
            'image_base64': None
        }
    
    # Convert to DataFrame for easier aggregation
    df = pd.DataFrame(rows)
    
    # Clean and parse numeric values defensively
    def parse_numeric(val):
        if pd.isna(val):
            return None
        if isinstance(val, (int, float)):
            return float(val)
        if isinstance(val, str):
            # Remove currency symbols, commas, units
            cleaned = val.replace('$', '').replace(',', '').replace('kms', '').strip()
            try:
                return float(cleaned)
            except ValueError:
                return None
        return None
    
    df[y_col] = df[y_col].apply(parse_numeric)
    
    # Remove rows with missing values in key columns
    df = df.dropna(subset=[x_col, y_col])
    
    # Aggregate by x_col using specified function
    agg_map = {
        'mean': 'mean',
        'sum': 'sum',
        'count': 'count',
        'median': 'median',
        'min': 'min',
        'max': 'max'
    }
    agg_method = agg_map.get(agg_func, 'mean')
    
    if series_col and series_col in columns:
        # Multi-series aggregation
        grouped = df.groupby([x_col, series_col])[y_col].agg(agg_method).reset_index()
        pivot_data = grouped.pivot(index=x_col, columns=series_col, values=y_col)
        plot_data = pivot_data
    else:
        # Single series aggregation
        plot_data = df.groupby(x_col)[y_col].agg(agg_method).sort_values(ascending=False)
    
    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Plot based on chart kind
    if chart_kind == 'bar':
        if isinstance(plot_data, pd.DataFrame):
            plot_data.plot(kind='bar', ax=ax)
        else:
            plot_data.plot(kind='bar', ax=ax, color='steelblue')
    elif chart_kind == 'line':
        if isinstance(plot_data, pd.DataFrame):
            plot_data.plot(kind='line', ax=ax, marker='o')
        else:
            plot_data.plot(kind='line', ax=ax, marker='o', color='steelblue')
    elif chart_kind == 'barh':
        if isinstance(plot_data, pd.DataFrame):
            plot_data.plot(kind='barh', ax=ax)
        else:
            plot_data.plot(kind='barh', ax=ax, color='steelblue')
    elif chart_kind == 'scatter':
        ax.scatter(df[x_col], df[y_col], alpha=0.6, s=50)
    elif chart_kind == 'histogram':
        ax.hist(df[y_col].dropna(), bins=20, color='steelblue', edgecolor='black')
    else:
        # Default to bar
        if isinstance(plot_data, pd.DataFrame):
            plot_data.plot(kind='bar', ax=ax)
        else:
            plot_data.plot(kind='bar', ax=ax, color='steelblue')
    
    # Labels and title
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.set_xlabel(xlabel, fontsize=12)
    ax.set_ylabel(ylabel, fontsize=12)
    ax.grid(axis='y', alpha=0.3)
    
    if chart_kind == 'bar' or chart_kind == 'barh':
        plt.xticks(rotation=45, ha='right')
    
    plt.tight_layout()
    
    # Save to base64
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=100, bbox_inches='tight')
    buf.seek(0)
    image_base64 = base64.b64encode(buf.read()).decode('utf-8')
    plt.close(fig)
    
    return {
        'image_base64': image_base64,
        'chart_kind': chart_kind,
        'x_column': x_col,
        'y_column': y_col,
        'aggregation': agg_func,
        'rows_plotted': len(df)
    }
