"""
csp.orchestrator.capability
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Two capability kinds live here:

1. RegisteredCapability  — developer-defined Python function, decorated
                           with @app.capability(). Executed directly.

2. SynthesizedCapability — JSON-RPC 2.0 spec generated by the synthesizer
                           at runtime. Carries real Python that is executed
                           in a sandbox. Stored in the registry for reuse.

The JSON-RPC 2.0 spec is the canonical artifact for synthesized capabilities.
It describes the capability contract completely — params, result schema,
execution target, and the generated code. The same spec can be persisted,
inspected, and re-run.

JSON-RPC 2.0 Capability Spec shape:
{
    "jsonrpc": "2.0",
    "method": "csp.capability.invoke",
    "params": {
        "capability_id": "train_churn_model",
        "version": "1.0.0",
        "description": "...",
        "params_schema": {
            "dataset": {"type": "string"},
            "target_column": {"type": "string"}
        },
        "result_schema": {
            "accuracy": {"type": "number"}
        },
        "execution": {
            "target": "python",
            "entrypoint": "run",
            "code": "def run(args):\\n    ...\\n    return {...}",
            "steps": ["load data", "train model", "evaluate"]
        }
    }
}
"""

from __future__ import annotations

import inspect
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Callable, Coroutine, Optional


class CapabilityKind(Enum):
    REGISTERED   = auto()   # developer-defined Python function
    SYNTHESIZED  = auto()   # LLM-generated JSON-RPC 2.0 spec


@dataclass(slots=True)
class CapabilityParam:
    """A single parameter in a capability's schema."""
    name:        str
    type:        str                    # "string" | "number" | "boolean" | "object" | "array"
    description: Optional[str] = None
    required:    bool          = True
    default:     Any           = None


@dataclass(slots=True)
class RegisteredCapability:
    """
    A developer-defined capability backed by a Python coroutine.

    Created by @app.capability() decorator.
    """
    name:        str
    fn:          Callable[..., Coroutine[Any, Any, Any]]
    description: str                          = ""
    params:      list[CapabilityParam]        = field(default_factory=list)
    version:     str                          = "1.0.0"
    kind:        CapabilityKind               = CapabilityKind.REGISTERED
    registered_at: float                      = field(default_factory=time.time)

    def to_jsonrpc_spec(self) -> dict[str, Any]:
        """Serialize to JSON-RPC 2.0 capability spec for wire/storage."""
        return {
            "jsonrpc": "2.0",
            "method": "csp.capability.invoke",
            "params": {
                "capability_id": self.name,
                "version": self.version,
                "description": self.description,
                "kind": "registered",
                "params_schema": {
                    p.name: {
                        "type": p.type,
                        "description": p.description,
                        "required": p.required,
                    }
                    for p in self.params
                },
                "execution": {
                    "target": "python",
                    "transport": "stdio",
                },
            },
        }

    async def invoke(self, **kwargs: Any) -> Any:
        """
        Execute the underlying Python function.

        Filters kwargs to only the parameters the function actually accepts —
        unless the function declares **kwargs. This lets the executor inject
        contextual args (like _elicit_response) without breaking capabilities
        that don't declare them.
        """
        sig = inspect.signature(self.fn)
        accepts_var_kwargs = any(
            p.kind is inspect.Parameter.VAR_KEYWORD
            for p in sig.parameters.values()
        )
        if accepts_var_kwargs:
            call_kwargs = kwargs
        else:
            call_kwargs = {k: v for k, v in kwargs.items() if k in sig.parameters}
        return await self.fn(**call_kwargs)

    def __repr__(self) -> str:
        return f"<RegisteredCapability {self.name!r} v{self.version}>"


@dataclass(slots=True)
class SynthesizedCapability:
    """
    A capability generated at runtime by the synthesizer.

    The JSON-RPC 2.0 spec IS the capability — it describes everything
    needed to execute it: params, result schema, and the generated Python
    that runs in the sandbox.
    """
    name:          str
    spec:          dict[str, Any]             # full JSON-RPC 2.0 spec
    description:   str                        = ""
    version:       str                        = "1.0.0"
    kind:          CapabilityKind             = CapabilityKind.SYNTHESIZED
    synthesized_at: float                     = field(default_factory=time.time)
    id:            str                        = field(default_factory=lambda: str(uuid.uuid4()))
    # Credentials this capability needs injected as env vars before running.
    # Each entry: {"env_key": str, "service": str, "get_it_at": str, "description": str}
    credentials:   list                       = field(default_factory=list)

    @property
    def _execution(self) -> dict[str, Any]:
        return self.spec.get("params", {}).get("execution", {})

    @property
    def steps(self) -> list[str]:
        """Human-readable progress steps — streamed to the user while running."""
        return self._execution.get("steps", [f"executing {self.name}"])

    @property
    def target(self) -> str:
        """Execution target. Synthesized capabilities run real Python ('python')."""
        return self._execution.get("target", "python")

    @property
    def code(self) -> str:
        """The real Python implementation, if target == 'python'."""
        return self._execution.get("code", "")

    @property
    def entrypoint(self) -> str:
        return self._execution.get("entrypoint", "run")

    @property
    def params_schema(self) -> dict[str, Any]:
        return self.spec.get("params", {}).get("params_schema", {})

    @property
    def result_schema(self) -> dict[str, Any]:
        return self.spec.get("params", {}).get("result_schema", {})

    def to_jsonrpc_spec(self) -> dict[str, Any]:
        """Already a spec — return as-is."""
        return self.spec

    def __repr__(self) -> str:
        return f"<SynthesizedCapability {self.name!r} v{self.version} id={self.id[:8]}>"


# Union type used throughout orchestrator
AnyCapability = RegisteredCapability | SynthesizedCapability


def capability_from_function(
    name: str,
    fn: Callable,
    description: str = "",
) -> RegisteredCapability:
    """
    Build a RegisteredCapability by introspecting a Python function's
    type annotations. Called by the @app.capability() decorator.
    """
    sig    = inspect.signature(fn)
    params = []

    _type_map = {
        str:   "string",
        int:   "number",
        float: "number",
        bool:  "boolean",
        dict:  "object",
        list:  "array",
    }

    for param_name, param in sig.parameters.items():
        ann  = param.annotation
        ptype = _type_map.get(ann, "string") if ann is not inspect.Parameter.empty else "string"
        has_default = param.default is not inspect.Parameter.empty
        params.append(
            CapabilityParam(
                name=param_name,
                type=ptype,
                required=not has_default,
                default=param.default if has_default else None,
            )
        )

    doc = inspect.getdoc(fn) or description

    return RegisteredCapability(
        name=name,
        fn=fn,
        description=doc,
        params=params,
    )