"""
Synthesized capability: fetch_standings
Fetch and display World Cup 2026 group standings as a ranked table.

Auto-generated by CSP. This is the exact code the sandbox runs.
"""

def run(args):
    import requests
    import os
    
    # Read parameters with sensible defaults
    group = args.get("group", "A").upper()
    api_key = os.environ.get("FOOTBALL_DATA_API_KEY")
    
    # Validate group
    if group not in ["A", "B", "C", "D", "E", "F", "G", "H"]:
        return {
            "view": "stat",
            "title": "Standings Error",
            "data": {"value": "—", "label": "Invalid group", "sub": f"Group {group} not found"},
            "summary": f"Group {group} is not a valid World Cup 2026 group (A–H)."
        }
    
    if not api_key:
        return {
            "view": "stat",
            "title": "Standings Error",
            "data": {"value": "—", "label": "Missing API key", "sub": "football-data.org"},
            "summary": "FOOTBALL_DATA_API_KEY environment variable not set. Cannot fetch standings."
        }
    
    try:
        # Fetch standings from football-data.org
        headers = {"X-Auth-Token": api_key}
        url = "https://api.football-data.org/v4/competitions/WC/standings"
        response = requests.get(url, headers=headers, timeout=20)
        response.raise_for_status()
        data = response.json()
        
        # Find the requested group
        group_key = f"GROUP_{group}"
        standings_list = data.get("standings", [])
        group_standing = None
        
        for standing in standings_list:
            if standing.get("group") == group_key:
                group_standing = standing
                break
        
        if not group_standing:
            return {
                "view": "stat",
                "title": f"Group {group} Standings",
                "data": {"value": "—", "label": "No data", "sub": "Group not found in standings"},
                "summary": f"Group {group} standings not available in the current competition data."
            }
        
        # Extract table rows
        table_rows = group_standing.get("table", [])
        
        if not table_rows:
            return {
                "view": "stat",
                "title": f"Group {group} Standings",
                "data": {"value": "—", "label": "Empty group", "sub": "No teams in standings"},
                "summary": f"Group {group} has no teams in the standings yet."
            }
        
        # Build table view
        columns = ["Team", "P", "W", "D", "L", "GF", "GA", "GD", "Pts"]
        rows = []
        
        for entry in table_rows:
            team = entry.get("team", {})
            team_name = team.get("name", "Unknown")
            played = entry.get("playedGames", 0)
            won = entry.get("won", 0)
            draw = entry.get("draw", 0)
            lost = entry.get("lost", 0)
            gf = entry.get("goalsFor", 0)
            ga = entry.get("goalsAgainst", 0)
            gd = entry.get("goalDifference", 0)
            points = entry.get("points", 0)
            
            rows.append([
                team_name,
                played,
                won,
                draw,
                lost,
                gf,
                ga,
                gd,
                points
            ])
        
        # Build summary
        if rows:
            leader = rows[0][0]
            leader_pts = rows[0][8]
            summary = f"Group {group} standings: {leader} leads with {leader_pts} points."
        else:
            summary = f"Group {group} standings are empty."
        
        return {
            "view": "table",
            "title": f"World Cup 2026 – Group {group} Standings",
            "data": {
                "columns": columns,
                "rows": rows
            },
            "summary": summary
        }
    
    except requests.exceptions.Timeout:
        return {
            "view": "stat",
            "title": "Standings Error",
            "data": {"value": "—", "label": "Request timeout", "sub": "football-data.org"},
            "summary": "Request to football-data.org timed out. Please try again."
        }
    except requests.exceptions.HTTPError as e:
        error_msg = str(e)
        if "401" in error_msg or "403" in error_msg:
            error_detail = "Invalid or expired API key"
        else:
            error_detail = f"HTTP {e.response.status_code}"
        
        return {
            "view": "stat",
            "title": "Standings Error",
            "data": {"value": "—", "label": "API error", "sub": error_detail},
            "summary": f"Failed to fetch standings: {error_detail}."
        }
    except Exception as e:
        return {
            "view": "stat",
            "title": "Standings Error",
            "data": {"value": "—", "label": "Unexpected error", "sub": str(type(e).__name__)},
            "summary": f"An unexpected error occurred: {str(e)}"
        }
